// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqUeeetc2h7Z9rImjA_kD7qy_TgyO1JAM',
    appId: '1:1045645464126:web:ede2831a35d6030822376f',
    messagingSenderId: '1045645464126',
    projectId: 'fir-app-distribution-63d81',
    authDomain: 'fir-app-distribution-63d81.firebaseapp.com',
    storageBucket: 'fir-app-distribution-63d81.firebasestorage.app',
    measurementId: 'G-26GM4L36CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASd7L9ogpnW3x12QYcg6aoG04Goj8pR4c',
    appId: '1:1045645464126:android:f74d5f56127e60b122376f',
    messagingSenderId: '1045645464126',
    projectId: 'fir-app-distribution-63d81',
    storageBucket: 'fir-app-distribution-63d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nPJpQIOwaDXFUdUtoDbJnfNqeN1LBAc',
    appId: '1:1045645464126:ios:22f6f8f39675328022376f',
    messagingSenderId: '1045645464126',
    projectId: 'fir-app-distribution-63d81',
    storageBucket: 'fir-app-distribution-63d81.firebasestorage.app',
    iosBundleId: 'com.example.docDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1nPJpQIOwaDXFUdUtoDbJnfNqeN1LBAc',
    appId: '1:1045645464126:ios:22f6f8f39675328022376f',
    messagingSenderId: '1045645464126',
    projectId: 'fir-app-distribution-63d81',
    storageBucket: 'fir-app-distribution-63d81.firebasestorage.app',
    iosBundleId: 'com.example.docDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqUeeetc2h7Z9rImjA_kD7qy_TgyO1JAM',
    appId: '1:1045645464126:web:f3f7d837eb629a9c22376f',
    messagingSenderId: '1045645464126',
    projectId: 'fir-app-distribution-63d81',
    authDomain: 'fir-app-distribution-63d81.firebaseapp.com',
    storageBucket: 'fir-app-distribution-63d81.firebasestorage.app',
    measurementId: 'G-JFY0QVWZGQ',
  );
}
