
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane For Android Firebase App Distribution" 
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:1045645464126:android:f74d5f56127e60b122376f",
      firebase_cli_token: "1//03XsfxUinrJ7ACgYIARAAGAMSNwF-L9IrvRLqo9Ns0SFGjLpr-6PdeB-TXmdhFb5QVxKZHXDSPSNxJ7atwRwjEL5ftCV-FiQFlcE",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "karamsalama2024@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
